# Issue 1 and 2
command:
python main.py -o IGNORE_EXCEPTION_DETAIL -v

result:
Trying:
    decode('')
Expecting:
    ''
ok
Trying:
    decode('.- -... -.- .-..') # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
Expecting:
    'ABKL'
ok
Trying:
    decode('... --- ...')
Expecting:
    'SOS'
ok
Trying:
    decode('--------')  # doctest: +ELLIPSIS,
Expecting:
    Traceback (most recent call last):
        ...
    KeyError: '--------'
ok
Trying:
    encode('')
Expecting:
    ''
ok
Trying:
    encode('ABBA') # doctest: +ELLIPSIS, +NORMALIZE_WHITESPACE
Expecting:
    '.- -... -...   .-'
ok
Trying:
    encode('SOS')
Expecting:
    '... --- ...'
ok
Trying:
    encode('#')
Expecting:
    Traceback (most recent call last):
        ...
    KeyError: '#'
ok
1 items had no tests:
    __main__
2 items passed all tests:
   4 tests in __main__.decode
   4 tests in __main__.encode
8 tests in 3 items.
8 passed and 0 failed.
Test passed.

# Issue 3
command:
python -m unittest -v unittest_ohe.py

result:
test (unittest_ohe.TestStringMethods) ... ok
test_equal (unittest_ohe.TestStringMethods) ... ok
test_not_equal (unittest_ohe.TestStringMethods) ... ok
test_not_in (unittest_ohe.TestStringMethods) ... ok
test_order (unittest_ohe.TestStringMethods) ... ok

# Issue 4

command:
python -m pytest -v pytest_ohe.py

result:
============================================================================================== test session starts ===============================================================================================
platform win32 -- Python 3.10.7, pytest-7.1.3, pluggy-1.0.0 -- *****
cachedir: .pytest_cache
rootdir: *****
collected 4 items

pytest_ohe.py::test_equal_large PASSED                                                                                                                                                                      [ 25%]
pytest_ohe.py::test_single PASSED                                                                                                                                                                           [ 50%]
pytest_ohe.py::test_exception PASSED                                                                                                                                                                        [ 75%]
pytest_ohe.py::test_order PASSED                                                                                                                                                                            [100%]

=============================================================================================== 4 passed in 0.04s ================================================================================================

# Issue 5

command:
python -m unittest what_is_year_now.py

result:
...
----------------------------------------------------------------------
Ran 3 tests in 0.003s

OK
